### ISSUE TITLE
Is anyone actively working on maintaining this?

### ISSUE THREAD

**Issue by Capri2014** [wslee/gpuopt#1]

**Comment by wslee** [comment]
No, I will remove this repo in a moment. Can I ask why you ask?

**Comment by Capri2014** [comment]
Sure, we are trying to speed up our optimization problem and thought this one might potentially fit our needs.  So I am wondering if there is any examples/benchmark so we can have a quick view? Thanks.

**Comment by wslee** [comment]
Well, this repo is a simple copy of Polybench: 
http://www.cse.ohio-state.edu/~pouchet/software/polybench/
Please refer to the above address.
